# Generated by Django 4.2.15 on 2024-08-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='biography',
            new_name='bio',
        ),
    ]
